# Generated by Django 2.2.7 on 2020-04-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NfsServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=15)),
                ('mount_point', models.CharField(default='/mnt/', max_length=100)),
            ],
        ),
    ]
